In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("D:\Regex\covid_toy.csv")
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [3]:
df=df.drop(columns=['age','fever'],axis=1)

In [4]:
df.head()

   gender cough     city has_covid
0    Male  Mild  Kolkata        No
1    Male  Mild    Delhi       Yes
2    Male  Mild    Delhi        No
3  Female  Mild  Kolkata        No
4  Female  Mild   Mumbai        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [8]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [9]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [10]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [15]:
oe=OrdinalEncoder(categories=[['Male','Female'],['Mild','Strong'],
                              ['Kolkata','Bangalore','Delhi','Mumbai'],['No','Yes']])

In [16]:
oe

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [17]:
oe.fit(df)

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [19]:
new_df=oe.transform(df)

In [20]:
new_df=pd.DataFrame(new_df,columns=df.columns)

In [21]:
new_df

    gender  cough  city  has_covid
0      0.0    0.0   0.0        0.0
1      0.0    0.0   2.0        1.0
2      0.0    0.0   2.0        0.0
3      1.0    0.0   0.0        0.0
4      1.0    0.0   3.0        0.0
..     ...    ...   ...        ...
95     1.0    0.0   1.0        0.0
96     1.0    1.0   0.0        1.0
97     1.0    0.0   1.0        0.0
98     1.0    1.0   3.0        0.0
99     1.0    1.0   0.0        1.0

[100 rows x 4 columns]

# method-2 get_dummies()

In [ ]:
#Column==>Sub-category-1,Sub_Category-2==> Apply==>get_dummies()==>
#create new columns==> first_col(Sub-category1), second_col(sub_category2)
#gender==>Male, female ==> apply==>get_dummies()==>first_col(male),second_col(female)

In [22]:
df.head()

   gender cough     city has_covid
0    Male  Mild  Kolkata        No
1    Male  Mild    Delhi       Yes
2    Male  Mild    Delhi        No
3  Female  Mild  Kolkata        No
4  Female  Mild   Mumbai        No

In [25]:
pd.get_dummies(df, columns=['gender','cough','city'])

,has_covid,gender_Female,gender_Male,cough_Mild,cough_Strong,city_Bangalore,city_Delhi,city_Kolkata,city_Mumbai
0,No,False,True,True,False,False,False,True,False
1,Yes,False,True,True,False,False,True,False,False
2,No,False,True,True,False,False,True,False,False
3,No,True,False,True,False,False,False,True,False
4,No,True,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...
95,No,True,False,True,False,True,False,False,False
96,Yes,True,False,False,True,False,False,True,False
97,No,True,False,True,False,True,False,False,False
98,No,True,False,False,True,False,False,False,True
99,Yes,True,False,False,True,False,False,True,False

# method 3 - One Hot Encoding

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [31]:
oe=OneHotEncoder(drop='first',sparse=False)

In [32]:
df.head(3)

  gender cough     city has_covid
0   Male  Mild  Kolkata        No
1   Male  Mild    Delhi       Yes
2   Male  Mild    Delhi        No

In [33]:
df_new=oe.fit_transform(df[['gender','cough','city','has_covid']])

C:\Users\furza\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [34]:
df_new

array([[1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 1., 1.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 1., 1.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 1.],
       [1., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.]])