In [1]:
# What is Machine learning ? 

# (1). Feature Engineering ===> Process ===> 
# Data Normal Distribute (central tendancy(mean,median,mode) left side = right side equal data)
# (2). Models

In [2]:
# Feature Enginnering ===>

In [3]:
# (1). Standardization ==> mean , standard deviation value  ===> mean =  0 , standard deviation = 1

In [4]:
import numpy as np 
import pandas as pd

In [ ]:
df = pd.read_csv("C:\Users\furza\Regex\placement.csv")

In [6]:
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [8]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

# step-1 Separate dataset into Independent or dependent data

In [13]:
x = df.drop(columns = ['placed'] , axis=1)  #Independent columns  , axis=1  means column wise operation  , axis=0 means row wise operation in pandas
y = df['placed']   #Dependent data

# Step-2  Separate x,y data into train and test datasets

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42) 

#x = Independent data
# y = dependent data 
# test_size = 0.2 means we are dividing our data into 80% of total data into training set and 20% of total data into testing set.
# test_size = 0.3 means we are dividing our data into 70% of total data into training set and 30% of total data into testing set.
# random_state ==> It is used for fix our indexing .

In [16]:
# Model performance  = 80%  
# Now I will refresh data ==> it will change indexing ==> change peformance our model . ==> Without Random_state 

# With Random_State ==> it will fix the indexing ==> It will not change performance of model .

In [36]:
# np.random.seed(45)
# a = np.random.randint(1,10,3)
# a

In [37]:
x_train.head()

    cgpa  resume_score
55  6.94          6.87
88  8.07          6.07
26  6.27          6.47
42  6.90          6.91
69  8.06          9.06

In [46]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 4)

In [47]:
x_train.head()

    cgpa  resume_score
80  7.83          7.70
4   7.52          7.30
81  6.12          6.72
76  9.40          5.50
85  6.72          5.46

In [48]:
# Let suppose 
# 100 students ==> classroom 

# Instructor ==> 70 students (training data)
# 30 students ==> out the class (testing data)

In [49]:
# Some topics(Functions) ==> You have to teach those 30 students ==> ???

# (1). If you are reading carefully ==> then you can teach easily .

In [57]:
print("Total dataset = " , df.shape)
print("Independent data = " , x.shape)
print("Dependent data = " , y.shape)
print("Independent training data = " , x_train.shape)
print("Independent testing data = " , x_test.shape)
print("Dependent training data = " , y_train.shape)
print("Dependent testing data = " , y_test.shape)

Total dataset =  (100, 3)
Independent data =  (100, 2)
Dependent data =  (100,)
Independent training data =  (80, 2)
Independent testing data =  (20, 2)
Dependent training data =  (80,)
Dependent testing data =  (20,)

In [58]:
np.round(x_train.describe() , 1)

       cgpa  resume_score
count  80.0          80.0
mean    6.8           6.9
std     1.1           1.0
min     5.3           5.0
25%     5.9           6.2
50%     6.5           6.9
75%     7.8           7.5
max     9.4           9.1

# step-3 import standardization

In [59]:
from sklearn.preprocessing import StandardScaler

In [60]:
sc = StandardScaler()

In [63]:
x_train_sc = sc.fit_transform(x_train)   #here fit means learn the parameters and transform means evaluate the parameters .

In [64]:
# x_train_sc

In [65]:
x_train_new = pd.DataFrame(x_train_sc , columns = x_train.columns)

In [70]:
np.round(x_train_new.describe() , 1)

       cgpa  resume_score
count  80.0          80.0
mean   -0.0          -0.0
std     1.0           1.0
min    -1.4          -2.0
25%    -0.8          -0.7
50%    -0.3           0.0
75%     0.9           0.7
max     2.4           2.3

In [ ]:
df = pd.read_csv("C:\Users\furza\Regex\insurance.csv")

In [79]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [80]:
# choice-1  ==> you can drop these  categorical columns ['sex' , 'smoker' , 'region']

# choice-2 ==> you can transform these values into numerical ==> using map function map({'yes':1 , 'no':0})

In [81]:
df = df.drop(columns = ['sex' , 'smoker' , 'region'])

In [82]:
x = df.drop(columns = ['charges'] , axis = 1)
x.head()

   age     bmi  children
0   19  27.900         0
1   18  33.770         1
2   28  33.000         3
3   33  22.705         0
4   32  28.880         0

In [83]:
y = df['charges']
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64